query fetchPullRequests($name: String!, $owner: String!, $after: String) {
    repository(name: $name, owner: $owner) {
        pullRequests(first: 100, after: $after, orderBy: { field: UPDATED_AT, direction: DESC}, states: [MERGED, CLOSED]) {
            pageInfo {
                hasNextPage
                endCursor
            }
            edges {
                node {
                  author {
                      login
                  },
                  updatedAt,
                  createdAt,
                  state,
                }
            }
        }
    }
}